kind: Rollout
apiVersion: argoproj.io/v1alpha1
metadata:
  name: spp-webserver
  namespace: spp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spp-webserver
  template:
    metadata:
      labels:
        app: spp-webserver
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: alpha.eksctl.io/nodegroup-name
                operator: In
                values:
                - eksng-c5xlarge-spp-pmd-prod
      containers:
        - name: spp-webserver
          image: 972277210775.dkr.ecr.ap-southeast-1.amazonaws.com/spp-webserver:dockercicd
          ports:
            - name: httpport
              containerPort: 80
              protocol: TCP
          resources:
            limits:
              memory: 150Mi
            requests:
              cpu: 100m
              memory: 150Mi  
  strategy:
   canary:
    steps:
      - setWeight: 10
      - pause:
          duration: 2m
      - setWeight: 20
      - pause:
          duration: 2m
      - setWeight: 40
      - pause:
          duration: 2m
      - setWeight: 60
      - pause:
          duration: 2m
      - setWeight: 80
      - pause:
          duration: 2m
